---
- name: "Konfiguracja serwera AGH_Lebda"
  hosts: linux
  become: true

  vars:
    raid_devices: "/dev/sdb,/dev/sdc"
    vg_name: "adg_vg"
    lv_name: "adg_lv"
    mount_path: "/adguardhome"
    
    allowed_ports:
      - "22/tcp"    
      - "53/udp"     
      - "53/tcp"  
      - "80/tcp"    
      - "3000/tcp"  
      - "443/tcp"   

  tasks:
    - name: "Instalacja narzędzi dyskowych (lvm2)"
      apt:
        name: lvm2
        state: present
        update_cache: yes

    - name: "Tworzenie Grupy Woluminów (VG)"
      lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ raid_devices }}"

    - name: "Sprawdzenie czy wolumin logiczny już istnieje"
      shell: "lvs /dev/{{ vg_name }}/{{ lv_name }}"
      register: lv_exists
      ignore_errors: yes
      changed_when: false

    - name: "Tworzenie Woluminu Logicznego (LV) RAID1"
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: 100%VG
        opts: "--type raid1"
      when: lv_exists.rc != 0  

    - name: "Formatowanie woluminu (ext4)"
      filesystem:
        fstype: ext4
        dev: "/dev/{{ vg_name }}/{{ lv_name }}"

    - name: "Odmontowanie dysku (dla pewności)"
      mount:
        path: "{{ mount_path }}"
        state: unmounted

    - name: "Ponowne montowanie z uprawnieniami EXEC"
      mount:
        path: "{{ mount_path }}"
        src: "/dev/{{ vg_name }}/{{ lv_name }}"
        fstype: ext4
        opts: "defaults" 
        state: mounted

    - name: "Pobieranie oficjalnego skryptu instalacyjnego do /tmp"
      get_url:
        url: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
        dest: /tmp/install_agh.sh
        mode: '0755'

    - name: "Instalacja AdGuard Home do /opt"
      shell: "/tmp/install_agh.sh"
      args:
        creates: /opt/AdGuardHome/AdGuardHome

    - name: "Zatrzymanie AdGuarda przed migracją"
      service:
        name: AdGuardHome
        state: stopped

    - name: "Przeniesienie plików z /opt na wolumin RAID"
      shell: "cp -r /opt/AdGuardHome/* {{ mount_path }}/"

    - name: "Rejestracja usługi w nowej lokalizacji"
      shell: "./AdGuardHome -s install -w {{ mount_path }}"
      args:
        chdir: "{{ mount_path }}"

    - name: "Start AdGuarda z RAID"
      service:
        name: AdGuardHome
        state: started
        enabled: yes

    - name: "Instalacja UFW"
      apt:
        name: ufw
        state: present

    - name: "Blokada ruchu przychodzącego"
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: "Otwieranie portów SSH i AdGuard"
      ufw:
        rule: allow
        port: "{{ item | split('/') | first }}"
        proto: "{{ item | split('/') | last }}"
      loop: "{{ allowed_ports }}"
