---
- name: "Kopia zapasowa AdGuard Home - Źródło"
  hosts: agh_lebda 
  become: true 

  vars:
    discord_webhook_id: "1460748367331332208"
    discord_webhook_token: "Ly_lZnGshZhl-y9R-KwmWr4quCdQzXTxk6H3pgZKUBcwyX9YygH7WnT4GkcM6goKRyCZ"
    status_msg_fail: "Błąd wykonywania kopii zapasowej AGH na hoscie: {{ inventory_hostname }}"

    backup_src: "/adguardhome"
    local_dest_dir: "/tmp/backups/agh_lebda"
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"
    backup_filename: "agh_backup_{{ timestamp }}.tar.gz"

  tasks:
    - name: "Tworzenie i pobieranie kopii zapasowej"
      block:
        - name: "Sprawdzanie czy na serwerze sterującym istnieje katalog na backup"
          file:
            path: "{{ local_dest_dir }}"
            state: directory
            mode: '0755'
          delegate_to: localhost
          become: false 

        - name: "Pakowanie plików AdGuard Home do archiwum .tar.gz"
          community.general.archive:
            path: "{{ backup_src }}"
            dest: "/tmp/{{ backup_filename }}"
            format: gz
            force_archive: true

        - name: "Pobieranie archiwum na serwer Ansible"
          fetch:
            src: "/tmp/{{ backup_filename }}"
            dest: "{{ local_dest_dir }}/{{ backup_filename }}"
            flat: ye

        - name: "Usuwanie tymczasowego archiwum z serwera zdalnego"
          file:
            path: "/tmp/{{ backup_filename }}"
            state: absent

        - name: "Zapis nazwy pliku dla procedury restore"
          set_fact:
            shared_backup_file: "{{ backup_filename }}"
          delegate_to: localhost
          delegate_facts: true

        - name: "Sukces - Backup pobrany"
          debug:
            msg: "Backup gotowy: {{ local_dest_dir }}/{{ backup_filename }}"

      rescue:
        - name: "Zgloszenie bledu na Discord"
          community.general.discord:
            webhook_id: "{{ discord_webhook_id }}"
            webhook_token: "{{ discord_webhook_token }}"
            username: "Semaphore - Backup AGH"
            content: "{{ status_msg_fail }}"


- name: "Test odtwarzania na nowej maszynie"
  hosts: test_restore
  become: true

  vars:
    local_dest_dir: "/tmp/backups/agh_lebda"
    backup_filename: "{{ hostvars['localhost']['shared_backup_file'] }}"
    restore_location: "/opt/odzyskany_agh"

  tasks:
    - name: "Weryfikacja czy plik do odtworzenia istnieje"
      debug:
        msg: "Odtwarzanie pliku: {{ backup_filename }} na maszynie {{ inventory_hostname }}"

    - name: "Zatrzymanie usługi AdGuardHome jeśli już działa"
      service:
        name: AdGuardHome
        state: stopped
      ignore_errors: yes

    - name: "Zatrzymanie i wyłączenie systemd-resolved"
      service:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: "Wyczyszczenie katalogu docelowego"
      file:
        path: "{{ restore_location }}"
        state: absent

    - name: "Stworzenie katalogu docelowego"
      file:
        path: "{{ restore_location }}"
        state: directory
        mode: '0755'

    - name: "Przesył i rozpakowanie backupu"
      unarchive:
        src: "{{ local_dest_dir }}/{{ backup_filename }}"
        dest: "{{ restore_location }}"
        owner: root
        group: root
    
    - name: "Nadawanie uprawnien wykonywalności dla pliku binarnego"
      file:
        path: "{{ restore_location }}/adguardhome/AdGuardHome"
        mode: '0755'
        owner: root
        group: root

    - name: "Zmiana starego IP na 0.0.0.0 - nasluchiwanie https)"
      replace:
        path: "{{ restore_location }}/adguardhome/AdGuardHome.yaml"
        regexp: '^\s*address:\s*\d{1,3}(\.\d{1,3}){3}:80'
        replace: '  address: 0.0.0.0:80'

    - name: "Zmiana starego IP na 0.0.0.0 - nasluchiwanie dns"
      replace:
        path: "{{ restore_location }}/adguardhome/AdGuardHome.yaml"
        regexp: '^\s*-\s*192\.168\.\d+\.\d+'
        replace: '  - 0.0.0.0'

    - name: "Instalacja AdGuard Home jako usługa systemowa"
      command:
        cmd: "./AdGuardHome -s install"
        chdir: "{{ restore_location }}/adguardhome"
      register: install_result
      failed_when: 
        - install_result.rc != 0
        - '"already exists" not in install_result.stderr'
        - '"already exists" not in install_result.stdout'

    - name: "Uruchomienie usługę AdGuardHome"
      service:
        name: AdGuardHome
        state: restarted
        enabled: yes

    - name: "Raport końcowy"
      debug:
        msg: "Backup i rozpakowanie ukończone sukcesem, AdGuard dostępny pod : http://{{ ansible_host }}"
