- name: "Konserwacja systemów Debian"
  hosts: linux
  become: true
  
  vars:
    discord_webhook_id: "1460748367331332208"
    discord_webhook_token: "Ly_lZnGshZhl-y9R-KwmWr4quCdQzXTxk6H3pgZKUBcwyX9YygH7WnT4GkcM6goKRyCZ"
    status_msg_fail: "Krytyczny błąd aktualizacji na hostcie: {{ inventory_hostname }} ({{ ansible_host }})"

  tasks:
    - name: "Aktualizacja i czyszczenie"
      block:
        - name: "Odświeżenie list pakietów"
          apt:
            update_cache: ye
            cache_valid_time: 3600

        - name: "Instalacja poprawek (safe-upgrade)"
          apt:
            upgrade: safe
            dpkg_options: 'force-confold,force-confdef'
          environment:
            DEBIAN_FRONTEND: noninteractive
          register: pkg_result

        - name: "Usuwanie zbędnych pakietów"
          apt:
            autoremove: yes
            autoclean: yes
          when: pkg_result.changed

        - name: "Sprawdzenie potrzeby restartu"
          stat:
            path: /var/run/reboot-required
          register: reboot_file

        - name: "Informacja o konieczności restartu"
          debug:
            msg: "System {{ inventory_hostname }} wymaga restartu po aktualizacji kernela!"
          when: reboot_file.stat.exists

      rescue:
        - name: "Zgloszenie bledu na discord"
          community.general.discord:
            webhook_id: "{{ discord_webhook_id }}"
            webhook_token: "{{ discord_webhook_token }}"
            username: "Semaphore - Aktualizacja AGH_Lebda"
            content: "{{ status_msg_fail }}"
